-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 20:32:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop_daniel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop_daniel` ;

-- -----------------------------------------------------
-- Schema shop_daniel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop_daniel` DEFAULT CHARACTER SET utf8 ;
USE `shop_daniel` ;

-- -----------------------------------------------------
-- Table `shop_daniel`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`categoria` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`categoria` (
  `idcategoria` BIGINT(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `datecreate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`rol` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`rol` (
  `Idrol` BIGINT(20) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Estado` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`Idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`persona` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`persona` (
  `idpersona` BIGINT(20) NOT NULL,
  `identificacion` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `telefono` BIGINT(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `nit` VARCHAR(20) NOT NULL,
  `nombrefiscal` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `token` VARCHAR(50) NOT NULL,
  `rolid` BIGINT(20) NOT NULL,
  `datacreate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idpersona`),
  INDEX `rolid` (`rolid` ASC) VISIBLE,
  CONSTRAINT `persona_ibfk_1`
    FOREIGN KEY (`rolid`)
    REFERENCES `shop_daniel`.`rol` (`Idrol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`pedido` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`pedido` (
  `idpedido` BIGINT(20) NOT NULL,
  `personaid` BIGINT(20) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `monto` DECIMAL(11,2) NOT NULL,
  `tipopagoid` BIGINT(20) NOT NULL,
  `estado` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idpedido`),
  INDEX `personaid` (`personaid` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`personaid`)
    REFERENCES `shop_daniel`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`producto` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`producto` (
  `idproducto` BIGINT(20) NOT NULL,
  `categoriaid` BIGINT(20) NOT NULL,
  `codigo` VARCHAR(25) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `datecreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `estado` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idproducto`),
  INDEX `categoriaid` (`categoriaid` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`categoriaid`)
    REFERENCES `shop_daniel`.`categoria` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`detalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`detalle_pedido` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`detalle_pedido` (
  `id` BIGINT(20) NOT NULL,
  `pedidoid` BIGINT(20) NOT NULL,
  `productoid` BIGINT(20) NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pedidoid` (`pedidoid` ASC) VISIBLE,
  INDEX `productoid` (`productoid` ASC) VISIBLE,
  CONSTRAINT `detalle_pedido_ibfk_1`
    FOREIGN KEY (`pedidoid`)
    REFERENCES `shop_daniel`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detalle_pedido_ibfk_2`
    FOREIGN KEY (`productoid`)
    REFERENCES `shop_daniel`.`producto` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`detalle_temp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`detalle_temp` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`detalle_temp` (
  `id` BIGINT(20) NOT NULL,
  `productoid` BIGINT(20) NOT NULL,
  `precio` DECIMAL(11,2) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productoid` (`productoid` ASC) VISIBLE,
  CONSTRAINT `detalle_temp_ibfk_1`
    FOREIGN KEY (`productoid`)
    REFERENCES `shop_daniel`.`producto` (`idproducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`modulo` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`modulo` (
  `Idmodulo` BIGINT(20) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`Idmodulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`permiso` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`permiso` (
  `idpermiso` BIGINT(20) NOT NULL,
  `rolid` BIGINT(20) NOT NULL,
  `moduloid` BIGINT(20) NOT NULL,
  `lectura` INT(11) NOT NULL DEFAULT 0,
  `escritura` INT(11) NOT NULL DEFAULT 0,
  `actualizar` INT(11) NOT NULL DEFAULT 0,
  `eliminar` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idpermiso`),
  INDEX `rolid` (`rolid` ASC) VISIBLE,
  INDEX `moduloid` (`moduloid` ASC) VISIBLE,
  CONSTRAINT `permiso_ibfk_1`
    FOREIGN KEY (`rolid`)
    REFERENCES `shop_daniel`.`rol` (`Idrol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `permiso_ibfk_2`
    FOREIGN KEY (`moduloid`)
    REFERENCES `shop_daniel`.`modulo` (`Idmodulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `shop_daniel`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_daniel`.`Login` ;

CREATE TABLE IF NOT EXISTS `shop_daniel`.`Login` (
  `idLogin` BIGINT NOT NULL,
  `idpersona` BIGINT(20) NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_persona1_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_Login_persona1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `shop_daniel`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
